In [2]:
import cv2
import numpy as np
print(cv2.__version__)


4.10.0


In [11]:
img = cv2.imread('download.jpeg')
print(img)

[[[ 73  38  18]
  [ 69  34  14]
  [ 68  33  13]
  ...
  [ 52  38  39]
  [ 63  50  42]
  [ 65  52  38]]

 [[ 67  31  13]
  [ 69  34  14]
  [ 73  37  19]
  ...
  [ 62  46  47]
  [ 51  35  29]
  [ 53  36  27]]

 [[ 63  29  13]
  [ 70  37  18]
  [ 77  43  27]
  ...
  [ 67  49  50]
  [ 63  42  41]
  [ 65  42  40]]

 ...

 [[216 213 208]
  [216 213 208]
  [216 213 208]
  ...
  [218 215 211]
  [221 213 214]
  [221 213 214]]

 [[219 216 211]
  [219 216 211]
  [219 216 211]
  ...
  [218 215 211]
  [221 213 214]
  [221 213 214]]

 [[215 212 207]
  [216 213 208]
  [216 213 208]
  ...
  [220 217 213]
  [223 215 216]
  [223 215 216]]]


In [ ]:
img = cv2.resize(img,(800,400))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #BGR format to Gray
cv2.imshow('original', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
# roi = img y1:y2, x1:x2
roi= img[100:400, 230:550]
cv2.imshow('roi', roi)
cv2.waitKey(0)
cv2.destroyAllWindows()